# alacritty.toml
# commented lines are the defaults
# man 5 alacritty (>0.13) for full config manual
# https://gist.github.com/iuliandita/a4c1dd0e25460af91ebeeef51e0ef7ec
#
#import = [
#"~/.config/alacritty/catpuccin-mocha.toml",
#"~/.config/alacritty/keybindings.toml",
#]

# [shell]
# program               = "/usr/bin/zsh"
# args                  = [ "--login", ]
#
#working_directory     = "None"
#live_config_reload    = true
#ipc_socket            = true

[env]
TERM = "xterm-256color"
[window]
dimensions            = { columns = 120, lines = 36 }
position              = "None"
dynamic_padding       = true
decorations           = "Full"
opacity               = 1
blur                  = true
#startup_mode          = "Windowed"
#title                 = "Alacritty"
#dynamic_title         = true
#class                 = { instance = "Alacritty", general = "Alacritty" }
#decorations_theme_variant = "None"
#resize_increments     = false
#option_as_alt         = "None"
dynamic_title = true
# 当窗口进入全屏模式时，应用以下配置
[scrolling]
history               = 65535
#multiplier            = 3

[font]
normal                = { family = "Maple Mono NF CN", style = "Regular" }
bold                  = { family = "Maple Mono NF CN", style = "Bold" }
italic                = { family = "Maple Mono NF CN", style = "Italic" }
bold_italic           = { family = "Maple Mono NF CN", style = "Bold Italic" }
size                  = 11
# offset                = { x = 0, y = 0 }
# glyph_offset          = { x = 0, y = 0 }
builtin_box_drawing   = true


#transparent_background_colors = false
#
# Colors (TokyoNight)

[colors.bright]
black = '#414868'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
magenta = '#bb9af7'
red = '#f7768e'
white = '#c0caf5'
yellow = '#e0af68'

[colors.cursor]
cursor = '#c0caf5'
text = '#15161e'

[colors.normal]
black = '#15161e'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
magenta = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'

[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.selection]
background = '#33467c'
text = '#c0caf5'
[colors]
draw_bold_text_with_bright_colors = true
[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true

[cursor.style]
shape                 = "Beam"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor]
blink_interval        = 500
blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[terminal]
#osc52                 = "OnlyCopy"

[mouse]
hide_when_typing      = true
# bindings = [
#   { mouse = "Middle", action = "PasteSelection" },
# ]

[hints]
#alphabet              = "jfkdls;ahgurieowpq"

#[[hints.enabled]]
#command               = "xdg-open"
## command             = "open" # On macOS
## command             = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
#hyperlinks            = true
#post_processing       = true
#persist               = false
#mouse.enabled         = true
#binding               = { key = "U", mods = "Control|Shift" }
#regex                 = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
  #{ key = "T",        mods = "Command",       action = "ToggleFullscreen"},
  { key = '/', mods= "Control",chars= "\u001f" } # 将<C_/>映射为<C_->,即发送字符^_ 

]


[debug]
#render_timer          = false
#persistent_logging    = false
# log_level             = "Warn"
# renderer              = "None"
# print_events          = false
# highlight_damage      = true
#prefer_egl            = false
